export const metadata = {
  title: 'Duay',
  description: 'Generated by Next.js',
}
import './globals.css'
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
